### ISSUE TITLE
Create a new freestyle job in Jenkins for test 4.1

### ISSUE THREAD

**Issue by mtouloup** [sonata-nfv/tng-tests#103]
https://jenkins.sonata-nfv.eu/job/test-test_sla_e2e-4.1/

**Comment by felipevicens** [comment]
Hey @mtouloup trigger it and check if works

**Comment by felipevicens** [comment]
Missing get logs from graylogs if something went wrong. 
Waiting for graylogs lib for tests

**Comment by mtouloup** [comment]
Logs Added, Test Executed, Test Passed
