### ISSUE TITLE
Develop the Test Cases

### ISSUE THREAD

**Issue by mtouloup** [sonata-nfv/tng-tests#104]

**Comment by felipevicens** [comment]
Where do you have the test case? can you put a link here? :)

**Comment by mtouloup** [comment]
Replied in #99

**Comment by mtouloup** [comment]
hey @felipevicens , i have several successes executing all three of the SLA cases... Do you think we can consider the tests done and close the SLA issues?

**Comment by felipevicens** [comment]
Tests cases are ready, let's track them in their particular tasks
