### ISSUE TITLE
[User management] Test admin role

### ISSUE THREAD

**Issue by ekapassa** [sonata-nfv/tng-tests#286]
- [x]     Register a user with a role:admin
- [x]     Check valid token
- [x]     Login if token not valid
- [x]   Obtain packages, services, slices, SLAs, policies
- [x]     All the above should be allowed as the role is 'admin'
- [x]   Logout
- [x]    Delete the users

**Comment by jbonnet** [comment]
@ekapassa please use another role other than admin when registering a user: only users with role admin will be able to create or update other users' role to admin

**Comment by ekapassa** [comment]
@jbonnet hmm...I didn't get it fully, sorry :/     
You mean that if for example User A is logged in, and wants to create (i.e. register) a new User B with admin role, the User A should be always admin ???

**Comment by jbonnet** [comment]
@ekapassa Exactly... Otherwise anyone could be admin, right?
The usual flow is:

1. the platform has one admin user, `tango`/`admin`;
1. different users are created;
1. the admin user `tango` makes at least one of those new users an admin and deletes it self

**Comment by ekapassa** [comment]
@jbonnet okk got it :) The other roles cannot create an admin, but can they create other users (developer, customer)??

**Comment by jbonnet** [comment]
Yes, that's the idea, @ekapassa 
Many thanks

**Comment by ekapassa** [comment]
@jbonnet Ok the test is done. Should I keep jose/123 in order to run??

**Comment by mtouloup** [comment]
Test Reviewed, Exexuted and Passed.
