### ISSUE TITLE
Unexpected field

### ISSUE THREAD

**Issue by MiguelRivasQuobis** [sonata-nfv/tng-tests#64]
The field **slad** is not in the schema [sla schema](https://github.com/sonata-nfv/tng-schema/blob/master/sla-template-descriptor/sla-template-schema.yml)
https://github.com/sonata-nfv/tng-tests/blob/6e09fe015134dcca6e16d8449fddac136c8cb47f/slas/silver_sla_example.yml#L6**

**Comment by ekapassa** [comment]
Hello @MiguelRivasQuobis . Yes, this is because the `slad field` is inserted by the Catalogue and not by the SLAM, when the descriptor is upload it.

**Comment by MiguelRivasQuobis** [comment]
Okey... Do you have some descriptor previous to the catalogue? It is to test the validator with SLAs.

**Comment by ekapassa** [comment]
Check here:    

- https://github.com/sonata-nfv/tng-sla-mgmt/blob/master/sla-template-generator/src/main/resources/bronze_sla_example.yml
- https://github.com/sonata-nfv/tng-sla-mgmt/blob/master/sla-template-generator/src/main/resources/silver_sla_example.yml
- https://github.com/sonata-nfv/tng-sla-mgmt/blob/master/sla-template-generator/src/main/resources/gold_sla_example.yml

**Comment by MiguelRivasQuobis** [comment]
Thank you!
I close the issue.
