### ISSUE TITLE
Create a file .robot with the definition of the sla test

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/tng-tests#99]

**Comment by felipevicens** [comment]
Hello @mtouloup paste the link to .robot definition file for the case.

**Comment by mtouloup** [comment]
Here are the links for the test cases. Basically they are the same with only one difference difining the type of the License on line numer 29. 

https://github.com/sonata-nfv/tng-tests/tree/master/tests/SP/test_cases_slas/test_sla_e2e_4.1
https://github.com/sonata-nfv/tng-tests/tree/master/tests/SP/test_cases_slas/test_sla_e2e_4.2
https://github.com/sonata-nfv/tng-tests/tree/master/tests/SP/test_cases_slas/test_sla_e2e_4.3

**Comment by felipevicens** [comment]
Approved!
